version: "3.8"

services:
  web:
    build:
      context: "./"
      dockerfile: Dockerfile
    image: "express-js-google-drive-api:1.0.0"
    environment:
      - "NODE_ENV=development"
    ports:
      - protocol: tcp
        published: 3500
        target: 3500