version: "3.8"

services:
  express-js-google-drive-api:
    container_name: 'express-js-google-drive-api'
    build:
      context: "."
      dockerfile: Dockerfile
    image: "express-js-google-drive-api:1.0.0"
    environment:
      - "NODE_ENV=development"
    ports:
      - protocol: tcp
        published: 2052
        target: 80
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run dev